name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v3"
      - name: Setup Python
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      - name: Install requirements
        run: python -m pip install homeassistant
      - name: Run hassfest
        run: python -m homeassistant.scripts.hassfest --action validate --integration-path ./custom_components/goteborg_energi
